services:
  frontend:
    build:
      context: .
      args:
        - PRODUCT_SERVICE_HOST=host.docker.internal:8080
    environment:
      - PRODUCT_SERVICE_HOST=host.docker.internal:8080
    ports:
      - "3000:3000"
      - "8080:8080"
