services:
  product:
    build:
      dockerfile: ./backend/services/product/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./secrets/sample.env:/prod/.env
      - ./secrets/firestore-sa.json:/prod/firestore-sa.json
    network_mode: "host"
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      target: run
      args:
        - PRODUCT_SERVICE_HOST=http://product:8080
    environment:
      - PRODUCT_SERVICE_HOST=http://product:8080
    ports:
      - "3000:3000"
    network_mode: "host"
    # Add when we have a product service Dockerfile
    depends_on:
      - product
networks:
  default:
    enable_ipv6: false
