services:
  product:
    build:
      dockerfile: ./backend/services/product/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./secrets/sample.env:/prod/.env
      - ./secrets/firestore-sa.json:/prod/firestore-sa.json
    networks:
      - internal
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      target: dev
    environment:
      - PRODUCT_SERVICE_HOST=product:8080
      - GRPC_TRACE=all
    ports:
      - "3000:3000"
    volumes:
      - ./specs:/app/specs
      - ./frontend:/app/frontend
    networks:
      - internal
    depends_on:
      - product

networks:
  internal:
    driver: bridge
