services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - PRODUCT_SERVICE_HOST=host.docker.internal:8080
    environment:
      - PRODUCT_SERVICE_HOST=host.docker.internal:8080
    ports:
      - "3000:3000"
    networks:
      - internal
    depends_on:
      - product
  product:
    build:
      context: .
      dockerfile: ./backend/services/product/Dockerfile
    networks:
      - internal

networks:
  internal: