// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: demand.proto

package demand_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_RECEIVED    Status = 0
	Status_ACCEPTED    Status = 1
	Status_REJECTED    Status = 2
	Status_IN_PROGRESS Status = 3
	Status_FULFILLED   Status = 4 // The order contained the demand, so it has been fulfilled and can be collected.
	Status_CONCLUDED   Status = 5 // The member has collected the order.
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "RECEIVED",
		1: "ACCEPTED",
		2: "REJECTED",
		3: "IN_PROGRESS",
		4: "FULFILLED",
		5: "CONCLUDED",
	}
	Status_value = map[string]int32{
		"RECEIVED":    0,
		"ACCEPTED":    1,
		"REJECTED":    2,
		"IN_PROGRESS": 3,
		"FULFILLED":   4,
		"CONCLUDED":   5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_demand_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_demand_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{0}
}

type DemandsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *string                `protobuf:"bytes,1,opt,name=member,proto3,oneof" json:"member,omitempty"` // member identification, initially with an E-mail`
	ExtendItems   *bool                  `protobuf:"varint,2,opt,name=extendItems,proto3,oneof" json:"extendItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandsReq) Reset() {
	*x = DemandsReq{}
	mi := &file_demand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandsReq) ProtoMessage() {}

func (x *DemandsReq) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandsReq.ProtoReflect.Descriptor instead.
func (*DemandsReq) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{0}
}

func (x *DemandsReq) GetMember() string {
	if x != nil && x.Member != nil {
		return *x.Member
	}
	return ""
}

func (x *DemandsReq) GetExtendItems() bool {
	if x != nil && x.ExtendItems != nil {
		return *x.ExtendItems
	}
	return false
}

type DemandsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Demands       []*Demand              `protobuf:"bytes,1,rep,name=demands,proto3" json:"demands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandsRes) Reset() {
	*x = DemandsRes{}
	mi := &file_demand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandsRes) ProtoMessage() {}

func (x *DemandsRes) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandsRes.ProtoReflect.Descriptor instead.
func (*DemandsRes) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{1}
}

func (x *DemandsRes) GetDemands() []*Demand {
	if x != nil {
		return x.Demands
	}
	return nil
}

type CreateDemandReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"` // member identification, initially with an E-mail - TODO: should be infered from auth system later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDemandReq) Reset() {
	*x = CreateDemandReq{}
	mi := &file_demand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDemandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDemandReq) ProtoMessage() {}

func (x *CreateDemandReq) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDemandReq.ProtoReflect.Descriptor instead.
func (*CreateDemandReq) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDemandReq) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateDemandReq) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_demand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{3}
}

func (x *IdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Demand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ID    string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// @gotags: firestore:"items,omitempty"
	Items          []*Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	CreationDate   string  `protobuf:"bytes,3,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	FulfilmentDate *string `protobuf:"bytes,4,opt,name=fulfilmentDate,proto3,oneof" json:"fulfilmentDate,omitempty"`
	Member         string  `protobuf:"bytes,5,opt,name=member,proto3" json:"member,omitempty"` // member identification, initially with an E-mail.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Demand) Reset() {
	*x = Demand{}
	mi := &file_demand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demand) ProtoMessage() {}

func (x *Demand) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demand.ProtoReflect.Descriptor instead.
func (*Demand) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{4}
}

func (x *Demand) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Demand) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Demand) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *Demand) GetFulfilmentDate() string {
	if x != nil && x.FulfilmentDate != nil {
		return *x.FulfilmentDate
	}
	return ""
}

func (x *Demand) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type Item struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DemandID       string                 `protobuf:"bytes,2,opt,name=demandID,proto3" json:"demandID,omitempty"`
	ProductId      string                 `protobuf:"bytes,3,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount         float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Position       uint32                 `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"` // for sorting of the demand and position will never be a negative number.
	Status         Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	FulfilmentDate *string                `protobuf:"bytes,7,opt,name=fulfilmentDate,proto3,oneof" json:"fulfilmentDate,omitempty"`
	CreationDate   string                 `protobuf:"bytes,8,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_demand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Item) GetDemandID() string {
	if x != nil {
		return x.DemandID
	}
	return ""
}

func (x *Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Item) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Item) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Item) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_RECEIVED
}

func (x *Item) GetFulfilmentDate() string {
	if x != nil && x.FulfilmentDate != nil {
		return *x.FulfilmentDate
	}
	return ""
}

func (x *Item) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

var File_demand_proto protoreflect.FileDescriptor

const file_demand_proto_rawDesc = "" +
	"\n" +
	"\fdemand.proto\x1a\x1bgoogle/protobuf/empty.proto\"k\n" +
	"\n" +
	"DemandsReq\x12\x1b\n" +
	"\x06member\x18\x01 \x01(\tH\x00R\x06member\x88\x01\x01\x12%\n" +
	"\vextendItems\x18\x02 \x01(\bH\x01R\vextendItems\x88\x01\x01B\t\n" +
	"\a_memberB\x0e\n" +
	"\f_extendItems\"/\n" +
	"\n" +
	"DemandsRes\x12!\n" +
	"\ademands\x18\x01 \x03(\v2\a.DemandR\ademands\"F\n" +
	"\x0fCreateDemandReq\x12\x1b\n" +
	"\x05items\x18\x01 \x03(\v2\x05.ItemR\x05items\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb1\x01\n" +
	"\x06Demand\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1b\n" +
	"\x05items\x18\x02 \x03(\v2\x05.ItemR\x05items\x12\"\n" +
	"\fcreationDate\x18\x03 \x01(\tR\fcreationDate\x12+\n" +
	"\x0efulfilmentDate\x18\x04 \x01(\tH\x00R\x0efulfilmentDate\x88\x01\x01\x12\x16\n" +
	"\x06member\x18\x05 \x01(\tR\x06memberB\x11\n" +
	"\x0f_fulfilmentDate\"\x89\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bdemandID\x18\x02 \x01(\tR\bdemandID\x12\x1c\n" +
	"\tproductId\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\rR\bposition\x12\x1f\n" +
	"\x06status\x18\x06 \x01(\x0e2\a.StatusR\x06status\x12+\n" +
	"\x0efulfilmentDate\x18\a \x01(\tH\x00R\x0efulfilmentDate\x88\x01\x01\x12\"\n" +
	"\fcreationDate\x18\b \x01(\tR\fcreationDateB\x11\n" +
	"\x0f_fulfilmentDate*a\n" +
	"\x06Status\x12\f\n" +
	"\bRECEIVED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x03\x12\r\n" +
	"\tFULFILLED\x10\x04\x12\r\n" +
	"\tCONCLUDED\x10\x052\xb8\x01\n" +
	"\rDemandService\x12(\n" +
	"\n" +
	"GetDemands\x12\v.DemandsReq\x1a\v.DemandsRes\"\x00\x12\x1e\n" +
	"\tGetDemand\x12\x06.IdReq\x1a\a.Demand\"\x00\x12+\n" +
	"\fCreateDemand\x12\x10.CreateDemandReq\x1a\a.Demand\"\x00\x120\n" +
	"\fDeleteDemand\x12\x06.IdReq\x1a\x16.google.protobuf.Empty\"\x00B9Z7github.com/manaaan/ekolivs-oms/backend/specs/demand_apib\x06proto3"

var (
	file_demand_proto_rawDescOnce sync.Once
	file_demand_proto_rawDescData []byte
)

func file_demand_proto_rawDescGZIP() []byte {
	file_demand_proto_rawDescOnce.Do(func() {
		file_demand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demand_proto_rawDesc), len(file_demand_proto_rawDesc)))
	})
	return file_demand_proto_rawDescData
}

var file_demand_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_demand_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_demand_proto_goTypes = []any{
	(Status)(0),             // 0: Status
	(*DemandsReq)(nil),      // 1: DemandsReq
	(*DemandsRes)(nil),      // 2: DemandsRes
	(*CreateDemandReq)(nil), // 3: CreateDemandReq
	(*IdReq)(nil),           // 4: IdReq
	(*Demand)(nil),          // 5: Demand
	(*Item)(nil),            // 6: Item
	(*emptypb.Empty)(nil),   // 7: google.protobuf.Empty
}
var file_demand_proto_depIdxs = []int32{
	5, // 0: DemandsRes.demands:type_name -> Demand
	6, // 1: CreateDemandReq.items:type_name -> Item
	6, // 2: Demand.items:type_name -> Item
	0, // 3: Item.status:type_name -> Status
	1, // 4: DemandService.GetDemands:input_type -> DemandsReq
	4, // 5: DemandService.GetDemand:input_type -> IdReq
	3, // 6: DemandService.CreateDemand:input_type -> CreateDemandReq
	4, // 7: DemandService.DeleteDemand:input_type -> IdReq
	2, // 8: DemandService.GetDemands:output_type -> DemandsRes
	5, // 9: DemandService.GetDemand:output_type -> Demand
	5, // 10: DemandService.CreateDemand:output_type -> Demand
	7, // 11: DemandService.DeleteDemand:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_demand_proto_init() }
func file_demand_proto_init() {
	if File_demand_proto != nil {
		return
	}
	file_demand_proto_msgTypes[0].OneofWrappers = []any{}
	file_demand_proto_msgTypes[4].OneofWrappers = []any{}
	file_demand_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demand_proto_rawDesc), len(file_demand_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demand_proto_goTypes,
		DependencyIndexes: file_demand_proto_depIdxs,
		EnumInfos:         file_demand_proto_enumTypes,
		MessageInfos:      file_demand_proto_msgTypes,
	}.Build()
	File_demand_proto = out.File
	file_demand_proto_goTypes = nil
	file_demand_proto_depIdxs = nil
}
