// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: product.proto

package product_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_ACTIVE Status = 0
	Status_HIDDEN Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "ACTIVE",
		1: "HIDDEN",
	}
	Status_value = map[string]int32{
		"ACTIVE": 0,
		"HIDDEN": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_product_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_product_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

type UnitType int32

const (
	// pieces
	UnitType_PIECES     UnitType = 0
	UnitType_GRAMS      UnitType = 1
	UnitType_KILOGRAMS  UnitType = 2
	UnitType_LITER      UnitType = 3
	UnitType_MILLILITER UnitType = 4
)

// Enum value maps for UnitType.
var (
	UnitType_name = map[int32]string{
		0: "PIECES",
		1: "GRAMS",
		2: "KILOGRAMS",
		3: "LITER",
		4: "MILLILITER",
	}
	UnitType_value = map[string]int32{
		"PIECES":     0,
		"GRAMS":      1,
		"KILOGRAMS":  2,
		"LITER":      3,
		"MILLILITER": 4,
	}
)

func (x UnitType) Enum() *UnitType {
	p := new(UnitType)
	*p = x
	return p
}

func (x UnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_product_proto_enumTypes[1].Descriptor()
}

func (UnitType) Type() protoreflect.EnumType {
	return &file_product_proto_enumTypes[1]
}

func (x UnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitType.Descriptor instead.
func (UnitType) EnumDescriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

type ProductsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsRes) Reset() {
	*x = ProductsRes{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsRes) ProtoMessage() {}

func (x *ProductsRes) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsRes.ProtoReflect.Descriptor instead.
func (*ProductsRes) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductsRes) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductIDReq) Reset() {
	*x = ProductIDReq{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIDReq) ProtoMessage() {}

func (x *ProductIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIDReq.ProtoReflect.Descriptor instead.
func (*ProductIDReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductIDReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Product struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ID      string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku     *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Barcode *string                `protobuf:"bytes,4,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	// Sales price
	Price *Price `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	// Purchase price from supplier
	CostPrice     *Price   `protobuf:"bytes,6,opt,name=costPrice,proto3" json:"costPrice,omitempty"`
	ImageUrl      *string  `protobuf:"bytes,7,opt,name=imageUrl,proto3,oneof" json:"imageUrl,omitempty"`
	VatPercentage *string  `protobuf:"bytes,8,opt,name=vatPercentage,proto3,oneof" json:"vatPercentage,omitempty"`
	Status        Status   `protobuf:"varint,9,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	UnitType      UnitType `protobuf:"varint,10,opt,name=unitType,proto3,enum=UnitType" json:"unitType,omitempty"`
	CreatedAt     *string  `protobuf:"bytes,11,opt,name=createdAt,proto3,oneof" json:"createdAt,omitempty"`
	UpdatedAt     *string  `protobuf:"bytes,12,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *Product) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Product) GetCostPrice() *Price {
	if x != nil {
		return x.CostPrice
	}
	return nil
}

func (x *Product) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *Product) GetVatPercentage() string {
	if x != nil && x.VatPercentage != nil {
		return *x.VatPercentage
	}
	return ""
}

func (x *Product) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_ACTIVE
}

func (x *Product) GetUnitType() UnitType {
	if x != nil {
		return x.UnitType
	}
	return UnitType_PIECES
}

func (x *Product) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type Price struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response with last 2 digits as decimals
	Amount float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Default "SEK"
	CurrencyID    string `protobuf:"bytes,2,opt,name=currencyID,proto3" json:"currencyID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *Price) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Price) GetCurrencyID() string {
	if x != nil {
		return x.CurrencyID
	}
	return ""
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n" +
	"\vProductsRes\x12$\n" +
	"\bproducts\x18\x01 \x03(\v2\b.ProductR\bproducts\"\x1e\n" +
	"\fProductIDReq\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xd0\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x00R\x03sku\x88\x01\x01\x12\x1d\n" +
	"\abarcode\x18\x04 \x01(\tH\x01R\abarcode\x88\x01\x01\x12\x1c\n" +
	"\x05price\x18\x05 \x01(\v2\x06.PriceR\x05price\x12$\n" +
	"\tcostPrice\x18\x06 \x01(\v2\x06.PriceR\tcostPrice\x12\x1f\n" +
	"\bimageUrl\x18\a \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12)\n" +
	"\rvatPercentage\x18\b \x01(\tH\x03R\rvatPercentage\x88\x01\x01\x12\x1f\n" +
	"\x06status\x18\t \x01(\x0e2\a.StatusR\x06status\x12%\n" +
	"\bunitType\x18\n" +
	" \x01(\x0e2\t.UnitTypeR\bunitType\x12!\n" +
	"\tcreatedAt\x18\v \x01(\tH\x04R\tcreatedAt\x88\x01\x01\x12!\n" +
	"\tupdatedAt\x18\f \x01(\tH\x05R\tupdatedAt\x88\x01\x01B\x06\n" +
	"\x04_skuB\n" +
	"\n" +
	"\b_barcodeB\v\n" +
	"\t_imageUrlB\x10\n" +
	"\x0e_vatPercentageB\f\n" +
	"\n" +
	"_createdAtB\f\n" +
	"\n" +
	"_updatedAt\"?\n" +
	"\x05Price\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12\x1e\n" +
	"\n" +
	"currencyID\x18\x02 \x01(\tR\n" +
	"currencyID* \n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06HIDDEN\x10\x01*K\n" +
	"\bUnitType\x12\n" +
	"\n" +
	"\x06PIECES\x10\x00\x12\t\n" +
	"\x05GRAMS\x10\x01\x12\r\n" +
	"\tKILOGRAMS\x10\x02\x12\t\n" +
	"\x05LITER\x10\x03\x12\x0e\n" +
	"\n" +
	"MILLILITER\x10\x042\x9b\x01\n" +
	"\x0eProductService\x125\n" +
	"\vGetProducts\x12\x16.google.protobuf.Empty\x1a\f.ProductsRes\"\x00\x12+\n" +
	"\x0eGetProductByID\x12\r.ProductIDReq\x1a\b.Product\"\x00\x12%\n" +
	"\rUpdateProduct\x12\b.Product\x1a\b.Product\"\x00B:Z8github.com/manaaan/ekolivs-oms/backend/specs/product_apib\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_product_proto_goTypes = []any{
	(Status)(0),           // 0: Status
	(UnitType)(0),         // 1: UnitType
	(*ProductsRes)(nil),   // 2: ProductsRes
	(*ProductIDReq)(nil),  // 3: ProductIDReq
	(*Product)(nil),       // 4: Product
	(*Price)(nil),         // 5: Price
	(*emptypb.Empty)(nil), // 6: google.protobuf.Empty
}
var file_product_proto_depIdxs = []int32{
	4, // 0: ProductsRes.products:type_name -> Product
	5, // 1: Product.price:type_name -> Price
	5, // 2: Product.costPrice:type_name -> Price
	0, // 3: Product.status:type_name -> Status
	1, // 4: Product.unitType:type_name -> UnitType
	6, // 5: ProductService.GetProducts:input_type -> google.protobuf.Empty
	3, // 6: ProductService.GetProductByID:input_type -> ProductIDReq
	4, // 7: ProductService.UpdateProduct:input_type -> Product
	2, // 8: ProductService.GetProducts:output_type -> ProductsRes
	4, // 9: ProductService.GetProductByID:output_type -> Product
	4, // 10: ProductService.UpdateProduct:output_type -> Product
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	file_product_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		EnumInfos:         file_product_proto_enumTypes,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
